version: '3'
services:
  Ros-container:
    build:
      context: .
    image: elaina/ros-container
    container_name: ros-container
    environment:
      - DISPLAY=${DISPLAY}
      # - XAUTHORITY=/root/.Xauthority  # 确保环境变量设置
    volumes:
      # - ${XAUTHORITY}:/root/.Xauthority
      - $HOME/.Xauthority:/root/.Xauthority  # 使用绝对路径
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - .:/home/Elaina/Ros
    network_mode: host
    pid: "host"      # 添加 pid 命名空间共享
    ipc: "host"      # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina"
    working_dir: "/home/Elaina" # 指定默认工作目录